# Generated by Django 2.1.6 on 2019-03-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-timestamp',)},
        ),
    ]
