# Generated by Django 2.1.6 on 2019-03-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_auto_20190327_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
    ]
