# Generated by Django 2.1.6 on 2019-03-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_auto_20190327_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-timestamp',)},
        ),
    ]
