# Generated by Django 2.1.6 on 2019-03-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationconnection',
            options={'ordering': ['reservation_interval', 'reservation_interval__start']},
        ),
    ]
